name: flutter_keep
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  flutter_vector_icons: ^2.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  lottie: ^2.1.0
  path_provider: ^2.0.11
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/animations/
